name: Comment on the Pull Request

# read-write repo token
# See: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
on:
  workflow_run:
    workflows: [".NET Core"]
    types:
      - completed

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    # Only comment on the PR if this is a PR event
    if: >
      github.event.workflow_run.event == 'pull_request'

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: pr

    - name: Read PR Number into GitHub environment variables
      run: echo "PR_NUMBER=$(cat pr-number)" >> $GITHUB_ENV
    - name: Confirm the PR Number (Debugging)
      run: echo $PR_NUMBER

    - name: Add Test Result Comment
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        number: ${{ env.PR_NUMBER }}
        hide_and_recreate: true
        hide_classify: "OUTDATED"
        header: Test Result
        path: test-result.md

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        number: ${{ env.PR_NUMBER }}
        hide_and_recreate: true
        hide_classify: "OUTDATED"
        header: Coverage Result
        path: code-coverage-results.md