name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: CI Build

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.101

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      id: build
      run: dotnet build --configuration Release --no-restore

    - name: Test (inc Code Coverage)
      id: test
      run: dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage > ./test-results.txt

    - name: Prettify Test results
      id: pretty_test
      run: |
        cat ./test-results.txt > ./test-results.md
        cat ./test-results.md >> $GITHUB_STEP_SUMMARY

    - name: Code Coverage Report
      id: codecov_report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'

    - name: Write to Job Summary
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY

    - name: Prepare artifacts
      run: |
        mkdir -p ./pr
        echo ${{ github.event.number }} > ./pr/pr-number
        cat test-results.md > ./pr/test-results.md
        cat code-coverage-results.md > ./pr/code-coverage-results.md

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: pr
        path: pr/
